-- AlterTable
ALTER TABLE "AppProductSubscriptionItem" ADD COLUMN     "tokenImage" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "tokenLive" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "tokenVideo" DOUBLE PRECISION NOT NULL DEFAULT 0;
