name: ${PROD_COMPOSE_PROJECT:-postmatic_vps_prod}

services:
  db:
    image: postgres:${PROD_POSTGRES_TAG:-15-alpine}
    environment:
      POSTGRES_DB: ${PROD_DATABASE_NAME}
      POSTGRES_USER: ${PROD_DATABASE_USER}
      POSTGRES_PASSWORD: ${PROD_DATABASE_PASSWORD}
    ports:
      - "127.0.0.1:${PROD_DATABASE_PORT:-25432}:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PROD_DATABASE_USER} -d ${PROD_DATABASE_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:${PROD_REDIS_TAG:-7-alpine}
    command: ["redis-server","--save","","--appendonly","no","--protected-mode","yes","--requirepass","${PROD_REDIS_PASSWORD}"]
    ports:
      - "127.0.0.1:${PROD_REDIS_PORT:-26379}:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${PROD_REDIS_PASSWORD}", "--no-auth-warning", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

  api:
    image: ${PROD_API_IMAGE:-ghcr.io/postmaticdev/postmatic-api}:${IMAGE_TAG:-production}
    env_file:
      - ../../apps/backend-service/.env.production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks: [default, traefik_proxy]
    labels:
      - "traefik.enable=true"

      # HTTP (80) -> redirect ke HTTPS
      - "traefik.http.routers.api-prod-web.rule=Host(`api.postmatic.id`)"
      - "traefik.http.routers.api-prod-web.entrypoints=web"
      - "traefik.http.routers.api-prod-web.middlewares=redirect-https@file"

      # HTTPS (443)
      - "traefik.http.routers.api-prod.rule=Host(`api.postmatic.id`)"
      - "traefik.http.routers.api-prod.entrypoints=websecure"
      - "traefik.http.routers.api-prod.tls=true"
      - "traefik.http.routers.api-prod.tls.certresolver=le-http"
      - "traefik.http.routers.api-prod.middlewares=security-headers@file,compress@file,limit-20mb@file"
      - "traefik.http.services.api-prod.loadbalancer.server.port=3000"
    restart: unless-stopped

  dashboard:
    image: ${PROD_DASH_IMAGE:-ghcr.io/postmaticdev/postmatic-dashboard}:${IMAGE_TAG:-production}
    env_file:
      - ../../apps/dashboard/.env.production
    depends_on:
      - api
    networks: [default, traefik_proxy]
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.dashboard-prod-web.rule=Host(`dashboard.postmatic.id`)"
      - "traefik.http.routers.dashboard-prod-web.entrypoints=web"
      - "traefik.http.routers.dashboard-prod-web.middlewares=redirect-https@file"

      - "traefik.http.routers.dashboard-prod.rule=Host(`dashboard.postmatic.id`)"
      - "traefik.http.routers.dashboard-prod.entrypoints=websecure"
      - "traefik.http.routers.dashboard-prod.tls=true"
      - "traefik.http.routers.dashboard-prod.tls.certresolver=le-http"
      - "traefik.http.routers.dashboard-prod.middlewares=security-headers@file,compress@file"
      - "traefik.http.services.dashboard-prod.loadbalancer.server.port=3000"
    restart: unless-stopped

  landing:
    image: ${PROD_LAND_IMAGE:-ghcr.io/postmaticdev/postmatic-landing}:${IMAGE_TAG:-production}
    env_file:
      - ../../apps/landing-page/.env.production
    networks: [default, traefik_proxy]
    labels:
      - "traefik.enable=true"

      # HTTP (80) → redirect ke HTTPS
      - "traefik.http.routers.landing-prod-web.rule=Host(`postmatic.id`,`www.postmatic.id`)"
      - "traefik.http.routers.landing-prod-web.entrypoints=web"
      - "traefik.http.routers.landing-prod-web.middlewares=redirect-https@file"

      # HTTPS apex → service
      - "traefik.http.routers.landing-prod.rule=Host(`postmatic.id`)"
      - "traefik.http.routers.landing-prod.entrypoints=websecure"
      - "traefik.http.routers.landing-prod.tls=true"
      - "traefik.http.routers.landing-prod.tls.certresolver=le-http"
      - "traefik.http.routers.landing-prod.middlewares=security-headers@file,compress@file"
      - "traefik.http.services.landing-prod.loadbalancer.server.port=3000"

      # HTTPS www → redirect ke apex
      - "traefik.http.routers.landing-prod-www.rule=Host(`www.postmatic.id`)"
      - "traefik.http.routers.landing-prod-www.entrypoints=websecure"
      - "traefik.http.routers.landing-prod-www.tls=true"
      - "traefik.http.routers.landing-prod-www.tls.certresolver=le-http"
      - "traefik.http.routers.landing-prod-www.middlewares=landing-www-redirect@file"
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true

volumes:
  pgdata_prod:
